const walls = [
    {
        "x": 0,
        "y": 0,
        "width": 40,
        "height": 3,
    },
    {
        "x": 0,
        "y": 0,
        "width": 3,
        "height": 40,
    },
    {
        "x": 40,
        "y": 0,
        "width": 40,
        "height": 3,
    },
    {
        "x": 80,
        "y": 0,
        "width": 40,
        "height": 3,
    },
    {
        "x": 80,
        "y": 40,
        "width": 40,
        "height": 3,
    },
    {
        "x": 120,
        "y": 0,
        "width": 40,
        "height": 3,
    },
    {
        "x": 160,
        "y": 0,
        "width": 3,
        "height": 40,
    },
    {
        "x": 160,
        "y": 0,
        "width": 40,
        "height": 3,
    },
    {
        "x": 160,
        "y": 40,
        "width": 40,
        "height": 3,
    },
    {
        "x": 160,
        "y": 0,
        "width": 3,
        "height": 40,
    },
    {
        "x": 200,
        "y": 0,
        "width": 40,
        "height": 3,
    },
    {
        "x": 200,
        "y": 40,
        "width": 40,
        "height": 3,
    },
    {
        "x": 240,
        "y": 0,
        "width": 40,
        "height": 3,
    },
    {
        "x": 280,
        "y": 0,
        "width": 3,
        "height": 40,
    },
    {
        "x": 280,
        "y": 0,
        "width": 40,
        "height": 3,
    },
    {
        "x": 280,
        "y": 0,
        "width": 3,
        "height": 40,
    },
    {
        "x": 320,
        "y": 0,
        "width": 40,
        "height": 3,
    },
    {
        "x": 320,
        "y": 40,
        "width": 40,
        "height": 3,
    },
    {
        "x": 360,
        "y": 0,
        "width": 40,
        "height": 3,
    },
    {
        "x": 400,
        "y": 0,
        "width": 3,
        "height": 40,
    },
    {
        "x": 40,
        "y": 40,
        "width": 3,
        "height": 40,
    },
    {
        "x": 0,
        "y": 40,
        "width": 3,
        "height": 40,
    },
    {
        "x": 80,
        "y": 40,
        "width": 3,
        "height": 40,
    },
    {
        "x": 40,
        "y": 40,
        "width": 3,
        "height": 40,
    },
    {
        "x": 80,
        "y": 40,
        "width": 40,
        "height": 3,
    },
    {
        "x": 120,
        "y": 40,
        "width": 3,
        "height": 40,
    },
    {
        "x": 80,
        "y": 40,
        "width": 3,
        "height": 40,
    },
    {
        "x": 120,
        "y": 80,
        "width": 40,
        "height": 3,
    },
    {
        "x": 120,
        "y": 40,
        "width": 3,
        "height": 40,
    },
    {
        "x": 160,
        "y": 40,
        "width": 40,
        "height": 3,
    },
    {
        "x": 200,
        "y": 40,
        "width": 3,
        "height": 40,
    },
    {
        "x": 200,
        "y": 40,
        "width": 40,
        "height": 3,
    },
    {
        "x": 200,
        "y": 40,
        "width": 3,
        "height": 40,
    },
    {
        "x": 280,
        "y": 40,
        "width": 3,
        "height": 40,
    },
    {
        "x": 240,
        "y": 80,
        "width": 40,
        "height": 3,
    },
    {
        "x": 320,
        "y": 40,
        "width": 3,
        "height": 40,
    },
    {
        "x": 280,
        "y": 40,
        "width": 3,
        "height": 40,
    },
    {
        "x": 320,
        "y": 40,
        "width": 40,
        "height": 3,
    },
    {
        "x": 320,
        "y": 40,
        "width": 3,
        "height": 40,
    },
    {
        "x": 400,
        "y": 40,
        "width": 3,
        "height": 40,
    },
    {
        "x": 360,
        "y": 80,
        "width": 40,
        "height": 3,
    },
    {
        "x": 40,
        "y": 80,
        "width": 3,
        "height": 40,
    },
    {
        "x": 0,
        "y": 80,
        "width": 3,
        "height": 40,
    },
    {
        "x": 80,
        "y": 80,
        "width": 3,
        "height": 40,
    },
    {
        "x": 40,
        "y": 80,
        "width": 3,
        "height": 40,
    },
    {
        "x": 120,
        "y": 80,
        "width": 3,
        "height": 40,
    },
    {
        "x": 80,
        "y": 80,
        "width": 3,
        "height": 40,
    },
    {
        "x": 120,
        "y": 80,
        "width": 40,
        "height": 3,
    },
    {
        "x": 120,
        "y": 80,
        "width": 3,
        "height": 40,
    },
    {
        "x": 200,
        "y": 80,
        "width": 3,
        "height": 40,
    },
    {
        "x": 160,
        "y": 120,
        "width": 40,
        "height": 3,
    },
    {
        "x": 200,
        "y": 120,
        "width": 40,
        "height": 3,
    },
    {
        "x": 200,
        "y": 80,
        "width": 3,
        "height": 40,
    },
    {
        "x": 240,
        "y": 80,
        "width": 40,
        "height": 3,
    },
    {
        "x": 280,
        "y": 80,
        "width": 3,
        "height": 40,
    },
    {
        "x": 320,
        "y": 80,
        "width": 3,
        "height": 40,
    },
    {
        "x": 280,
        "y": 80,
        "width": 3,
        "height": 40,
    },
    {
        "x": 360,
        "y": 80,
        "width": 3,
        "height": 40,
    },
    {
        "x": 320,
        "y": 80,
        "width": 3,
        "height": 40,
    },
    {
        "x": 360,
        "y": 80,
        "width": 40,
        "height": 3,
    },
    {
        "x": 400,
        "y": 80,
        "width": 3,
        "height": 40,
    },
    {
        "x": 360,
        "y": 80,
        "width": 3,
        "height": 40,
    },
    {
        "x": 40,
        "y": 120,
        "width": 3,
        "height": 40,
    },
    {
        "x": 0,
        "y": 120,
        "width": 3,
        "height": 40,
    },
    {
        "x": 80,
        "y": 120,
        "width": 3,
        "height": 40,
    },
    {
        "x": 40,
        "y": 120,
        "width": 3,
        "height": 40,
    },
    {
        "x": 80,
        "y": 120,
        "width": 3,
        "height": 40,
    },
    {
        "x": 160,
        "y": 120,
        "width": 3,
        "height": 40,
    },
    {
        "x": 120,
        "y": 160,
        "width": 40,
        "height": 3,
    },
    {
        "x": 160,
        "y": 120,
        "width": 40,
        "height": 3,
    },
    {
        "x": 160,
        "y": 160,
        "width": 40,
        "height": 3,
    },
    {
        "x": 160,
        "y": 120,
        "width": 3,
        "height": 40,
    },
    {
        "x": 200,
        "y": 120,
        "width": 40,
        "height": 3,
    },
    {
        "x": 280,
        "y": 120,
        "width": 3,
        "height": 40,
    },
    {
        "x": 240,
        "y": 160,
        "width": 40,
        "height": 3,
    },
    {
        "x": 320,
        "y": 120,
        "width": 3,
        "height": 40,
    },
    {
        "x": 280,
        "y": 120,
        "width": 3,
        "height": 40,
    },
    {
        "x": 360,
        "y": 120,
        "width": 3,
        "height": 40,
    },
    {
        "x": 320,
        "y": 120,
        "width": 3,
        "height": 40,
    },
    {
        "x": 400,
        "y": 120,
        "width": 3,
        "height": 40,
    },
    {
        "x": 360,
        "y": 120,
        "width": 3,
        "height": 40,
    },
    {
        "x": 40,
        "y": 160,
        "width": 3,
        "height": 40,
    },
    {
        "x": 0,
        "y": 200,
        "width": 40,
        "height": 3,
    },
    {
        "x": 0,
        "y": 160,
        "width": 3,
        "height": 40,
    },
    {
        "x": 80,
        "y": 160,
        "width": 3,
        "height": 40,
    },
    {
        "x": 40,
        "y": 160,
        "width": 3,
        "height": 40,
    },
    {
        "x": 120,
        "y": 160,
        "width": 3,
        "height": 40,
    },
    {
        "x": 80,
        "y": 160,
        "width": 3,
        "height": 40,
    },
    {
        "x": 120,
        "y": 160,
        "width": 40,
        "height": 3,
    },
    {
        "x": 120,
        "y": 160,
        "width": 3,
        "height": 40,
    },
    {
        "x": 160,
        "y": 160,
        "width": 40,
        "height": 3,
    },
    {
        "x": 160,
        "y": 200,
        "width": 40,
        "height": 3,
    },
    {
        "x": 240,
        "y": 160,
        "width": 3,
        "height": 40,
    },
    {
        "x": 240,
        "y": 160,
        "width": 40,
        "height": 3,
    },
    {
        "x": 240,
        "y": 160,
        "width": 3,
        "height": 40,
    },
    {
        "x": 320,
        "y": 160,
        "width": 3,
        "height": 40,
    },
    {
        "x": 280,
        "y": 200,
        "width": 40,
        "height": 3,
    },
    {
        "x": 320,
        "y": 200,
        "width": 40,
        "height": 3,
    },
    {
        "x": 320,
        "y": 160,
        "width": 3,
        "height": 40,
    },
    {
        "x": 400,
        "y": 160,
        "width": 3,
        "height": 40,
    },
    {
        "x": 0,
        "y": 200,
        "width": 40,
        "height": 3,
    },
    {
        "x": 0,
        "y": 200,
        "width": 3,
        "height": 40,
    },
    {
        "x": 80,
        "y": 200,
        "width": 3,
        "height": 40,
    },
    {
        "x": 40,
        "y": 240,
        "width": 40,
        "height": 3,
    },
    {
        "x": 120,
        "y": 200,
        "width": 3,
        "height": 40,
    },
    {
        "x": 80,
        "y": 200,
        "width": 3,
        "height": 40,
    },
    {
        "x": 160,
        "y": 200,
        "width": 3,
        "height": 40,
    },
    {
        "x": 120,
        "y": 200,
        "width": 3,
        "height": 40,
    },
    {
        "x": 160,
        "y": 200,
        "width": 40,
        "height": 3,
    },
    {
        "x": 160,
        "y": 240,
        "width": 40,
        "height": 3,
    },
    {
        "x": 160,
        "y": 200,
        "width": 3,
        "height": 40,
    },
    {
        "x": 240,
        "y": 200,
        "width": 3,
        "height": 40,
    },
    {
        "x": 200,
        "y": 240,
        "width": 40,
        "height": 3,
    },
    {
        "x": 280,
        "y": 200,
        "width": 3,
        "height": 40,
    },
    {
        "x": 240,
        "y": 200,
        "width": 3,
        "height": 40,
    },
    {
        "x": 280,
        "y": 200,
        "width": 40,
        "height": 3,
    },
    {
        "x": 280,
        "y": 200,
        "width": 3,
        "height": 40,
    },
    {
        "x": 320,
        "y": 200,
        "width": 40,
        "height": 3,
    },
    {
        "x": 320,
        "y": 240,
        "width": 40,
        "height": 3,
    },
    {
        "x": 400,
        "y": 200,
        "width": 3,
        "height": 40,
    },
    {
        "x": 360,
        "y": 240,
        "width": 40,
        "height": 3,
    },
    {
        "x": 40,
        "y": 240,
        "width": 3,
        "height": 40,
    },
    {
        "x": 0,
        "y": 240,
        "width": 3,
        "height": 40,
    },
    {
        "x": 40,
        "y": 240,
        "width": 40,
        "height": 3,
    },
    {
        "x": 40,
        "y": 240,
        "width": 3,
        "height": 40,
    },
    {
        "x": 120,
        "y": 240,
        "width": 3,
        "height": 40,
    },
    {
        "x": 80,
        "y": 280,
        "width": 40,
        "height": 3,
    },
    {
        "x": 120,
        "y": 280,
        "width": 40,
        "height": 3,
    },
    {
        "x": 120,
        "y": 240,
        "width": 3,
        "height": 40,
    },
    {
        "x": 160,
        "y": 240,
        "width": 40,
        "height": 3,
    },
    {
        "x": 200,
        "y": 240,
        "width": 3,
        "height": 40,
    },
    {
        "x": 200,
        "y": 240,
        "width": 40,
        "height": 3,
    },
    {
        "x": 200,
        "y": 240,
        "width": 3,
        "height": 40,
    },
    {
        "x": 280,
        "y": 240,
        "width": 3,
        "height": 40,
    },
    {
        "x": 240,
        "y": 280,
        "width": 40,
        "height": 3,
    },
    {
        "x": 280,
        "y": 280,
        "width": 40,
        "height": 3,
    },
    {
        "x": 280,
        "y": 240,
        "width": 3,
        "height": 40,
    },
    {
        "x": 320,
        "y": 240,
        "width": 40,
        "height": 3,
    },
    {
        "x": 320,
        "y": 280,
        "width": 40,
        "height": 3,
    },
    {
        "x": 360,
        "y": 240,
        "width": 40,
        "height": 3,
    },
    {
        "x": 400,
        "y": 240,
        "width": 3,
        "height": 40,
    },
    {
        "x": 40,
        "y": 280,
        "width": 3,
        "height": 40,
    },
    {
        "x": 0,
        "y": 280,
        "width": 3,
        "height": 40,
    },
    {
        "x": 40,
        "y": 280,
        "width": 3,
        "height": 40,
    },
    {
        "x": 80,
        "y": 280,
        "width": 40,
        "height": 3,
    },
    {
        "x": 80,
        "y": 320,
        "width": 40,
        "height": 3,
    },
    {
        "x": 120,
        "y": 280,
        "width": 40,
        "height": 3,
    },
    {
        "x": 120,
        "y": 320,
        "width": 40,
        "height": 3,
    },
    {
        "x": 200,
        "y": 280,
        "width": 3,
        "height": 40,
    },
    {
        "x": 160,
        "y": 320,
        "width": 40,
        "height": 3,
    },
    {
        "x": 240,
        "y": 280,
        "width": 3,
        "height": 40,
    },
    {
        "x": 200,
        "y": 280,
        "width": 3,
        "height": 40,
    },
    {
        "x": 240,
        "y": 280,
        "width": 40,
        "height": 3,
    },
    {
        "x": 280,
        "y": 280,
        "width": 3,
        "height": 40,
    },
    {
        "x": 240,
        "y": 280,
        "width": 3,
        "height": 40,
    },
    {
        "x": 280,
        "y": 280,
        "width": 40,
        "height": 3,
    },
    {
        "x": 280,
        "y": 280,
        "width": 3,
        "height": 40,
    },
    {
        "x": 320,
        "y": 280,
        "width": 40,
        "height": 3,
    },
    {
        "x": 360,
        "y": 280,
        "width": 3,
        "height": 40,
    },
    {
        "x": 400,
        "y": 280,
        "width": 3,
        "height": 40,
    },
    {
        "x": 360,
        "y": 280,
        "width": 3,
        "height": 40,
    },
    {
        "x": 40,
        "y": 320,
        "width": 3,
        "height": 40,
    },
    {
        "x": 0,
        "y": 320,
        "width": 3,
        "height": 40,
    },
    {
        "x": 80,
        "y": 320,
        "width": 3,
        "height": 40,
    },
    {
        "x": 40,
        "y": 360,
        "width": 40,
        "height": 3,
    },
    {
        "x": 40,
        "y": 320,
        "width": 3,
        "height": 40,
    },
    {
        "x": 80,
        "y": 320,
        "width": 40,
        "height": 3,
    },
    {
        "x": 80,
        "y": 320,
        "width": 3,
        "height": 40,
    },
    {
        "x": 120,
        "y": 320,
        "width": 40,
        "height": 3,
    },
    {
        "x": 160,
        "y": 320,
        "width": 3,
        "height": 40,
    },
    {
        "x": 160,
        "y": 320,
        "width": 40,
        "height": 3,
    },
    {
        "x": 160,
        "y": 360,
        "width": 40,
        "height": 3,
    },
    {
        "x": 160,
        "y": 320,
        "width": 3,
        "height": 40,
    },
    {
        "x": 240,
        "y": 320,
        "width": 3,
        "height": 40,
    },
    {
        "x": 200,
        "y": 360,
        "width": 40,
        "height": 3,
    },
    {
        "x": 280,
        "y": 320,
        "width": 3,
        "height": 40,
    },
    {
        "x": 240,
        "y": 320,
        "width": 3,
        "height": 40,
    },
    {
        "x": 320,
        "y": 320,
        "width": 3,
        "height": 40,
    },
    {
        "x": 280,
        "y": 320,
        "width": 3,
        "height": 40,
    },
    {
        "x": 320,
        "y": 360,
        "width": 40,
        "height": 3,
    },
    {
        "x": 320,
        "y": 320,
        "width": 3,
        "height": 40,
    },
    {
        "x": 400,
        "y": 320,
        "width": 3,
        "height": 40,
    },
    {
        "x": 360,
        "y": 360,
        "width": 40,
        "height": 3,
    },
    {
        "x": 0,
        "y": 400,
        "width": 40,
        "height": 3,
    },
    {
        "x": 0,
        "y": 360,
        "width": 3,
        "height": 40,
    },
    {
        "x": 40,
        "y": 360,
        "width": 40,
        "height": 3,
    },
    {
        "x": 40,
        "y": 400,
        "width": 40,
        "height": 3,
    },
    {
        "x": 120,
        "y": 360,
        "width": 3,
        "height": 40,
    },
    {
        "x": 80,
        "y": 400,
        "width": 40,
        "height": 3,
    },
    {
        "x": 120,
        "y": 400,
        "width": 40,
        "height": 3,
    },
    {
        "x": 120,
        "y": 360,
        "width": 3,
        "height": 40,
    },
    {
        "x": 160,
        "y": 360,
        "width": 40,
        "height": 3,
    },
    {
        "x": 160,
        "y": 400,
        "width": 40,
        "height": 3,
    },
    {
        "x": 200,
        "y": 360,
        "width": 40,
        "height": 3,
    },
    {
        "x": 200,
        "y": 400,
        "width": 40,
        "height": 3,
    },
    {
        "x": 240,
        "y": 400,
        "width": 40,
        "height": 3,
    },
    {
        "x": 280,
        "y": 400,
        "width": 40,
        "height": 3,
    },
    {
        "x": 320,
        "y": 360,
        "width": 40,
        "height": 3,
    },
    {
        "x": 320,
        "y": 400,
        "width": 40,
        "height": 3,
    },
    {
        "x": 360,
        "y": 360,
        "width": 40,
        "height": 3,
    },
    {
        "x": 400,
        "y": 360,
        "width": 3,
        "height": 40,
    },
    {
        "x": 360,
        "y": 400,
        "width": 40,
        "height": 3,
    }
]
export const generateRandomWalls = () => {
    return walls
}